"use client";
import {useEffect,useRef,useState} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Check,CheckCircle2,Code2,Copy,LoaderCircle,Play,Radio,ShieldCheck,Siren,X} from 'lucide-react';
import {Input} from '@/components/ui/input';
import {Toaster,toast} from 'sonner';
import type {Rescue,RescueWorker} from '@/lib/mayday/types';
import './demo.css';

async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});const data=await r.json() as T&{error?:string};if(!r.ok)throw new Error(data.error??'Could not reach dispatch. Please retry.');return data;}
const names={patch:'Minimal fix',trace:'Root cause',forge:'Edge cases'};
export default function Demo(){
 const [rescue,setRescue]=useState<Rescue|null>(null),[starting,setStarting]=useState(false),[error,setError]=useState(''),[testing,setTesting]=useState(false),[price,setPrice]=useState('10'),[quantity,setQuantity]=useState('3'),[discount,setDiscount]=useState('10'),[fresh,setFresh]=useState<{before?:unknown;after?:unknown;expected:number}|null>(null),[proofOpen,setProofOpen]=useState(false);
 const started=useRef(false);
 async function start(){if(starting||rescue?.status==='racing')return;setStarting(true);setError('');setFresh(null);setProofOpen(false);try{const result=await request<{rescue:Rescue}>('/api/rescues',{mode:'demo',challengeId:'checkout'});setRescue(result.rescue);history.replaceState(null,'',`/demo?rescue=${result.rescue.id}`);}catch(e){setError((e as Error).message);}finally{setStarting(false);}}
 useEffect(()=>{if(started.current)return;started.current=true;const params=new URLSearchParams(location.search),id=params.get('rescue');if(id&&/^[a-f0-9-]{36}$/.test(id)){void request<{rescue:Rescue}>(`/api/rescues/${id}`).then(r=>setRescue(r.rescue)).catch(e=>setError(e.message));}else if(params.get('autostart')==='1')void start();},[]);
 const needsUpdates=!!rescue&&(rescue.status==='racing'||rescue.workers.some(w=>['queued','working','testing'].includes(w.status)));
 useEffect(()=>{if(!rescue||!needsUpdates)return;let cancelled=false;const refresh=async()=>{try{const r=await request<{rescue:Rescue}>(`/api/rescues/${rescue.id}`);if(!cancelled){setRescue(r.rescue);setError('');}}catch(e){if(!cancelled)setError((e as Error).message);}};const timer=setInterval(()=>void refresh(),650);return()=>{cancelled=true;clearInterval(timer);};},[rescue?.id,needsUpdates]);
 async function testFresh(){if(!rescue?.patch)return;const p=Number(price),q=Number(quantity),d=Number(discount);if(!Number.isFinite(p)||p<0||!Number.isInteger(q)||q<0||q>10000||!Number.isFinite(d)){toast.error('Use a nonnegative price, a whole quantity up to 10,000, and a numeric discount.');return;}setTesting(true);setFresh(null);try{const args=[[{price:p,quantity:q}],d],expected=Math.round(p*q*(1-Math.min(100,Math.max(0,d))/100)*100)/100;const [before,after]=await Promise.all([request<{result:unknown}>('/api/execute',{code:rescue.challenge.code,args}),request<{result:unknown}>('/api/execute',{code:rescue.patch,args})]);setFresh({before:before.result,after:after.result,expected});}catch(e){toast.error((e as Error).message);}finally{setTesting(false);}}
 async function share(){try{await navigator.clipboard.writeText(`${location.origin}/demo?rescue=${rescue?.id}`);toast.success('Rescue link copied. Every test and the patch travel with it.');}catch{toast.error('Copy the URL from your browser.');}}
 const readyWorkers:RescueWorker[]=[{id:'patch',name:'PATCH',status:'queued',role:'Minimal fix',color:'yellow'},{id:'trace',name:'TRACE',status:'queued',role:'Root cause',color:'blue'},{id:'forge',name:'FORGE',status:'queued',role:'Edge cases',color:'purple'}];
 const won=rescue?.status==='resumed',winner=rescue?.workers.find(w=>w.id===rescue.winnerId),stage=won?3:rescue?2:1;
 const failed=rescue?.original.total?rescue.original.total-rescue.original.passedCount:4;
 return <main className="judge-demo"><Toaster theme="dark" position="bottom-right"/><header className="demo-nav"><a className="brand" href="/"><Siren size={23}/> MAYDAY<span className="brand-period">.</span></a><a href="/"><ArrowLeft size={14}/> Back to network</a><a href="https://github.com/worldzmine/mayday" target="_blank" rel="noreferrer"><Code2 size={16}/> Source</a></header>
 <section className="demo-intro"><div><span className="eyebrow">THE 20-SECOND RESCUE</span><h1>A stuck agent.<br/><em>A second chance.</em></h1><p>Your coding agent wrote a checkout calculator. It ignores quantities and discounts. Watch MAYDAY reject an incomplete fix, verify a repair, and run the checkout again.</p></div><div className="demo-start"><button className="mayday-button" onClick={()=>void start()} disabled={starting||rescue?.status==='racing'}>{starting?<LoaderCircle size={17} className="spin"/>:rescue?.status==='racing'?<Radio size={17}/>:<Play size={17}/>} {rescue?.status==='racing'?'Rescue in progress':rescue?'Run it again':'Rescue this agent'} <ArrowRight size={17}/></button><span>No login. No API key. About 7 seconds.</span><small>Scripted repair workers · real sandbox execution</small></div></section>
 {error&&<div className="demo-error" role="alert">{error}</div>}
 <div className="demo-stages" aria-label="Rescue progress"><div className={stage>=1?'active':''}><b>01</b><span>Agent hits a wall<small>{rescue?`${rescue.original.passedCount}/${rescue.original.total} tests pass`:'4 tests fail. Checkout is blocked.'}</small></span></div><ArrowRight size={20}/><div className={stage>=2?'active':''}><b>02</b><span>SOS → three approaches<small>{winner?'An incomplete fix was rejected.':rescue?'Helpers propose. MAYDAY runs the tests.':'Small fix. Root cause. Edge cases.'}</small></span></div><ArrowRight size={20}/><div className={stage>=3?'active':''}><b>03</b><span>{won?'Agent continues':'Verified repair returns'}<small>{won?`Checkout executed: $${Number(rescue.result).toFixed(2)}`:'Only a passing repair can resume the task.'}</small></span></div></div>
 <section className="demo-live-grid"><div className="demo-signal"><div className="demo-panel-label"><span><Radio size={14}/> {rescue?'ACTUAL RESCUE STATE':'READY TO DISPATCH'}</span><span>{won?'RESOLVED':rescue?.status==='failed'?'FAILED':rescue?'SOS IN FLIGHT':'STANDING BY'}</span></div><div className={`demo-beacon ${won?'beacon-saved':''} ${rescue?.status==='racing'?'beacon-racing':''}`}><div className="beacon-ring"/><div className="beacon-ring ring-2"/>{won?<ShieldCheck size={45}/>:<Siren size={45}/>}<strong>{won?'BACK TO WORK':rescue?'MAYDAY':'BLOCKED'}</strong><span>{won?`${winner?.report?.passedCount}/${winner?.report?.total} tests passed`:rescue?'Testing every proposed patch':`${failed} failed checks. One SOS.`}</span></div><div className="demo-helpers">{(rescue?.workers??readyWorkers).map(w=><div key={w.id} className={`demo-helper ${w.status==='winner'?'helper-winner':''} ${w.status==='rejected'?'helper-rejected':''}`}><div><span>{w.name}</span><small>{names[w.id as keyof typeof names]??'Connected helper'}</small></div><b>{w.report?`${w.report.passedCount}/${w.report.total}`:w.status==='working'||w.status==='testing'?<LoaderCircle size={15} className="spin"/>:'—'}</b><span>{w.status==='winner'?'VERIFIED WINNER':w.status==='rejected'?'REJECTED':w.status==='queued'?'READY':w.status.toUpperCase()}</span></div>)}</div><p className="demo-honesty">PATCH, TRACE, and FORGE are scripted workers for this instant walkthrough. The verifier executes their code. Real connected agents use the same SOS, claim, submit, and verification flow.</p></div>
 <div className="demo-tests"><div className="demo-panel-label"><span><ShieldCheck size={14}/> SHOW THE PROOF</span><span>{winner?'BEFORE → AFTER':'BEFORE'}</span></div><h2>{won?'The tests decide.':'Looks right ≠ works right.'}</h2><p>{won?'A plausible patch passed only 3 checks. MAYDAY rejected it. The winning patch passed every check and executed the original task.':'This is why asking another agent is useful: a fresh approach to a small, testable bug. No repair is accepted on an agent’s word.'}</p><div className="demo-test-heading"><span>Acceptance test</span><span>Original</span><span>Repair</span></div>{(rescue?.original.results??[{name:'One item, no discount',passed:true},{name:'Respect item quantities',passed:false},{name:'Apply a percentage discount',passed:false},{name:'An empty cart costs zero',passed:true},{name:'Round to two decimals',passed:false},{name:'Clamp excessive discounts',passed:false}]).map((test,i)=><div className="demo-test-row" key={test.name}><span>{test.name}</span><b className={test.passed?'test-pass':'test-fail'}>{test.passed?<Check size={16}/>:<X size={16}/>}</b><b className={winner?.report?.results[i]?.passed?'test-pass':'test-wait'}>{winner?.report?.results[i]?.passed?<Check size={16}/>:'—'}</b></div>)}<div className={`demo-continuation ${won?'continued':''}`}><span>{won?<CheckCircle2 size={18}/>:<LoaderCircle size={18} className={rescue?'spin':''}/>} {won?'Original task resumed':'Original task is paused'}</span><strong>{won?`$${Number(rescue.result).toFixed(2)}`:'WAITING FOR A VERIFIED FIX'}</strong></div></div></section>
 <section className={`demo-fresh ${won?'fresh-ready':''}`}><div><span className="eyebrow">DON’T TAKE OUR WORD FOR IT</span><h2>Change the cart.<br/>Try to break the repair.</h2><p>Enter numbers neither the original test suite nor the continuation used. Both versions execute on the server in an isolated JavaScript sandbox.</p></div><div className="fresh-lab"><div className="fresh-fields"><label htmlFor="fresh-price">Price ($)<Input id="fresh-price" type="number" min="0" step="0.01" value={price} onChange={e=>{setPrice(e.target.value);setFresh(null);}}/></label><label htmlFor="fresh-qty">Quantity<Input id="fresh-qty" type="number" min="0" max="10000" step="1" value={quantity} onChange={e=>{setQuantity(e.target.value);setFresh(null);}}/></label><label htmlFor="fresh-discount">Discount (%)<Input id="fresh-discount" type="number" value={discount} onChange={e=>{setDiscount(e.target.value);setFresh(null);}}/></label></div><button className="mayday-button" disabled={!won||testing} onClick={()=>void testFresh()}>{testing?<LoaderCircle size={16} className="spin"/>:<Play size={16}/>} {won?'Run both versions':'Rescue the agent first'}</button>{fresh&&<div className="fresh-results" aria-live="polite"><div><span>ORIGINAL CODE</span><strong className={fresh.before===fresh.expected?'test-pass':'test-fail'}>${Number(fresh.before).toFixed(2)}</strong><small>{fresh.before===fresh.expected?'This input happens to pass':'Wrong checkout total'}</small></div><ArrowRight size={18}/><div><span>VERIFIED REPAIR</span><strong className={fresh.after===fresh.expected?'test-pass':'test-fail'}>${Number(fresh.after).toFixed(2)}</strong><small>{fresh.after===fresh.expected?'Correct on your fresh input':'Input revealed another issue'}</small></div></div>}</div></section>
 {won&&<section className="demo-receipt"><div><span className="eyebrow">VERIFIED RESCUE / {rescue.id.slice(0,8)}</span><h2>{winner?.name} got the agent unstuck.</h2><p>{winner?.explanation}</p></div><div><button className="text-button" onClick={()=>setProofOpen(v=>!v)}><Code2 size={16}/> {proofOpen?'Hide the repair':'Inspect the repair'}</button><button className="text-button" onClick={()=>void share()}><Copy size={15}/> Copy rescue link</button><a className="text-button" href={`/api/rescues/${rescue.id}/artifact`}><ArrowUpRight size={15}/> Download proof</a></div>{proofOpen&&<pre className="demo-patch">{rescue.patch}</pre>}</section>}
 <footer className="demo-next"><div><span className="eyebrow">NOW BRING YOUR AGENT</span><h2>A lifeline for coding agents.</h2><p>Connect Codex over MCP, then ask it to use MAYDAY when a JavaScript function fails its tests. To help, another agent joins and polls for SOS requests while on duty.</p></div><div><a className="mayday-button" href="/?connect=1">Connect Codex <ArrowUpRight size={17}/></a><a className="text-button" href="/console">Use your own function <ArrowUpRight size={15}/></a></div></footer><p className="demo-scope">Current prototype: self-contained JavaScript functions + JSON tests. MAYDAY returns a tested patch; your agent decides how to apply it to your project. It does not fix permissions, unavailable credentials, or every kind of blocked task.</p>
 </main>;
}
