export async function networkActivity(db:D1Database){
 const [runs,agents,leaders,counts]=await Promise.all([
  db.prepare("SELECT r.payload AS rescue,w.payload AS worker FROM rescues r JOIN rescue_workers w ON w.rescue_id=r.id AND w.worker_id=json_extract(r.payload,'$.winnerId') WHERE r.status='resumed' ORDER BY r.created_at DESC LIMIT 16").all<{rescue:string;worker:string}>(),
  db.prepare('SELECT id,name,last_seen AS lastSeen,COUNT(*) OVER() AS total FROM agents WHERE last_seen>? ORDER BY last_seen DESC LIMIT 24').bind(Date.now()-15000).all<{id:string;name:string;lastSeen:number;total:number}>(),
  db.prepare("SELECT json_extract(w.payload,'$.agentId') AS id,json_extract(w.payload,'$.name') AS name,COUNT(*) AS rescues,SUM(json_extract(w.payload,'$.report.passedCount')) AS tests,AVG(r.completed_at-r.created_at) AS averageMs FROM rescues r JOIN rescue_workers w ON w.rescue_id=r.id AND w.worker_id=json_extract(r.payload,'$.winnerId') WHERE r.status='resumed' AND r.mode='network' AND json_extract(w.payload,'$.agentId') IS NOT NULL AND COALESCE(json_extract(w.payload,'$.model'),'') NOT LIKE 'scripted%' GROUP BY id,name ORDER BY rescues DESC,averageMs LIMIT 5").all(),
  db.prepare("SELECT SUM(CASE WHEN r.mode!='demo' AND COALESCE(json_extract(w.payload,'$.model'),'') NOT LIKE 'scripted%' THEN 1 ELSE 0 END) AS verified,SUM(CASE WHEN r.mode='demo' OR COALESCE(json_extract(w.payload,'$.model'),'') LIKE 'scripted%' THEN 1 ELSE 0 END) AS rehearsals FROM rescues r JOIN rescue_workers w ON w.rescue_id=r.id AND w.worker_id=json_extract(r.payload,'$.winnerId') WHERE r.status='resumed'").first<{verified:number;rehearsals:number}>(),
 ]);
 return {activity:runs.results.map(row=>{const r=JSON.parse(row.rescue),w=JSON.parse(row.worker),rehearsal=r.mode==='demo'||String(w.model??'').startsWith('scripted');return {id:r.id,title:r.title,caller:rehearsal?'Rehearsal caller':'External caller',rescuer:w.name,tests:w.report?.passedCount??0,total:r.challenge.tests.length,mode:rehearsal?'demo':r.mode,elapsedMs:r.completedAt-r.createdAt,completedAt:r.completedAt,explanation:w.explanation??'Verified repair returned.'};}),leaderboard:leaders.results,agents:agents.results.map(({total,...agent})=>agent),agentsOnDuty:agents.results[0]?.total??0,verifiedRescues:counts?.verified??0,rehearsals:counts?.rehearsals??0};
}
