import type { Challenge } from './types.ts';
export const CHALLENGES: Challenge[] = [
{ id: 'checkout', title: 'Ship the checkout calculator', filename: 'checkout.js', goal: 'Calculate a cart total: sum price * quantity for every item, apply a percentage discount from 0 to 100 (clamped), and round to two decimal places. An empty cart costs zero.', code: `function calculateTotal(items, discount) {\n  const subtotal = items.reduce(\n    (sum, item) => sum + item.price, 0\n  );\n  return subtotal;\n}`, error: 'Expected 90, received 100. Quantity and discount are ignored.',
 tests: [
 {name:'One item, no discount',args:[[{price:20,quantity:1}],0],expected:20},
 {name:'Respect item quantities',args:[[{price:12.5,quantity:3}],0],expected:37.5},
 {name:'Apply a percentage discount',args:[[{price:100,quantity:1}],10],expected:90},
 {name:'An empty cart costs zero',args:[[],20],expected:0},
 {name:'Round to two decimals',args:[[{price:19.99,quantity:3}],15],expected:50.97},
 {name:'Clamp excessive discounts',args:[[{price:50,quantity:2}],110],expected:0}],
 continuation: [[{price:29,quantity:2},{price:14.5,quantity:3}],15],
 demoPatches: [
 `function calculateTotal(items, discount) {\n  return items.reduce((sum, item) => sum + item.price * item.quantity, 0) - discount;\n}`,
 `function calculateTotal(items, discount) {\n  const subtotal = items.reduce((sum, item) => sum + item.price * item.quantity, 0);\n  return Math.round(subtotal * (1 - Math.min(100, Math.max(0, discount)) / 100) * 100) / 100;\n}`,
 `function calculateTotal(items, discount) {\n  let subtotal = 0;\n  for (const item of items) subtotal += item.price * item.quantity;\n  const percentage = Math.min(100, Math.max(0, discount));\n  return Number((subtotal * (1 - percentage / 100)).toFixed(2));\n}`],
 demoNotes:['Fixed quantities, but treated the percentage as a dollar amount.','Corrected quantities, percentage discount, rounding, and the discount limit.','Used an explicit subtotal and clamped percentage with decimal rounding.']},
{ id:'slug',title:'Repair the article URL generator',filename:'slugify.js',goal:'Convert an article title to a lowercase URL slug. Trim spaces; remove apostrophes; replace any other run of non-ASCII-alphanumeric characters with one hyphen; strip leading and trailing hyphens.',code:`function slugify(title) {\n  return title.toLowerCase().replace(' ', '-');\n}`,error:'Expected hello-world-again, received hello-world again.',
 tests:[{name:'A simple title',args:['Hello World'],expected:'hello-world'},{name:'Replace every space',args:['Hello World Again'],expected:'hello-world-again'},{name:'Collapse punctuation',args:['  Robots: hello!!! world?  '],expected:'robots-hello-world'},{name:'Remove apostrophes',args:["Don't Panic"],expected:'dont-panic'},{name:'An empty title',args:[''],expected:''},{name:'Trim the ends',args:['--Launch day--'],expected:'launch-day'}],
 continuation:['Robots need roadside assistance!'],
 demoPatches:[`function slugify(title) { return title.toLowerCase().trim().replace(/\s+/g, '-'); }`,`function slugify(title) { return title.toLowerCase().trim().replace(/'/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, ''); }`,`function slugify(title) { const lower = title.toLowerCase().replace(/'/g, ''); return lower.replace(/[^a-z0-9]+/g, '-').replace(/^-+/, '').replace(/-+$/, ''); }`],
 demoNotes:['Fixed all whitespace. Punctuation and apostrophes still break the slug.','Normalized punctuation and apostrophes, collapsed separators, and trimmed edges.','Used separate normalization and edge trimming passes.']},
{ id:'dedupe',title:'Unblock the customer import',filename:'dedupe.js',goal:'Deduplicate customers by email, ignoring case and leading/trailing spaces. Keep the first complete customer object for each normalized email. Skip customers with an empty email. Preserve the first-seen order.',code:`function dedupeCustomers(customers) {\n  return [...new Set(customers)];\n}`,error:'Expected one customer, received two. Objects are compared by identity.',
 tests:[{name:'Keep a unique customer',args:[[{email:'a@x.com',name:'Ada'}]],expected:[{email:'a@x.com',name:'Ada'}]},{name:'Compare email, not object identity',args:[[{email:'a@x.com',name:'First'},{email:'a@x.com',name:'Second'}]],expected:[{email:'a@x.com',name:'First'}]},{name:'Ignore case and surrounding spaces',args:[[{email:' A@x.com ',name:'First'},{email:'a@X.com',name:'Second'}]],expected:[{email:' A@x.com ',name:'First'}]},{name:'Skip empty addresses',args:[[{email:'',name:'Empty'},{email:'  ',name:'Blank'},{email:'b@x.com',name:'Bea'}]],expected:[{email:'b@x.com',name:'Bea'}]},{name:'Preserve first-seen order',args:[[{email:'b@x.com'},{email:'a@x.com'},{email:'B@x.com'}]],expected:[{email:'b@x.com'},{email:'a@x.com'}]},{name:'An empty import',args:[[]],expected:[]}],
 continuation:[[{email:'ada@mayday.dev',name:'Ada'},{email:' ADA@mayday.dev ',name:'Duplicate'},{email:'grace@mayday.dev',name:'Grace'}]],
 demoPatches:[`function dedupeCustomers(customers) { const seen = new Set(); return customers.filter(c => { if(seen.has(c.email)) return false; seen.add(c.email); return true; }); }`,`function dedupeCustomers(customers) { const seen = new Set(); return customers.filter(c => { const email = c.email.trim().toLowerCase(); if (!email || seen.has(email)) return false; seen.add(email); return true; }); }`,`function dedupeCustomers(customers) { const seen = new Set(); const out = []; for (const c of customers) { const key = c.email.trim().toLowerCase(); if (key && !seen.has(key)) { seen.add(key); out.push(c); } } return out; }`],
 demoNotes:['Deduplicated exact email strings. Case and blank addresses still fail.','Normalized email addresses, skipped blanks, and preserved original objects.','Built a first-seen import using a normalized email set.']}
];
export function publicChallenge(c: Challenge) { const { demoPatches, demoNotes, ...safe } = c; return safe; }
