import { createInterface } from 'node:readline';
import { MaydayClient } from '../sdk/mayday.mjs';
const client=new MaydayClient({baseUrl:process.env.MAYDAY_URL,apiToken:process.env.MAYDAY_API_TOKEN,workerToken:process.env.MAYDAY_WORKER_TOKEN});
const schema={type:'object',properties:{mode:{type:'string',enum:['demo','live','network'],description:'network dispatches to independent connected agents.'},challengeId:{type:'string'},challenge:{type:'object',properties:{title:{type:'string'},goal:{type:'string'},code:{type:'string'},tests:{type:'array',items:{type:'object',properties:{name:{type:'string'},args:{type:'array'},expected:{}},required:['args','expected']}},continuation:{type:'array'}},required:['goal','code','tests']}},additionalProperties:false};
const tools=[
 {name:'send_sos',description:'Submit a failing self-contained JavaScript function and its JSON acceptance tests to MAYDAY. Returns a rescue id immediately. Use get_rescue to collect the verified patch. Default mode network requires connected workers.',inputSchema:schema},
 {name:'get_rescue',description:'Inspect an SOS. When status is resumed, apply the returned patch to continue the original task. Read actual verification before applying.',inputSchema:{type:'object',properties:{id:{type:'string'}},required:['id']}},
 {name:'join_rescue_network',description:'Register this agent as a rescue worker. Its token is retained by this MCP process. Then list jobs, claim, and submit a repair.',inputSchema:{type:'object',properties:{name:{type:'string'}},required:['name']}},
 {name:'list_rescue_jobs',description:'List open SOS jobs available to this registered rescue agent.',inputSchema:{type:'object',properties:{}}},
 {name:'claim_rescue',description:'Claim one of three repair slots. A claim lasts 60 seconds. Returns broken code, goal, tests and continuation.',inputSchema:{type:'object',properties:{rescueId:{type:'string'}},required:['rescueId']}},
 {name:'submit_rescue_patch',description:'Submit a complete JavaScript function for sandbox verification. A passing repair can win and resume the task.',inputSchema:{type:'object',properties:{rescueId:{type:'string'},code:{type:'string'},explanation:{type:'string'}},required:['rescueId','code']}},
];
async function call(name,args){switch(name){case 'send_sos':return client.sendSOS({mode:'network',...args});case 'get_rescue':return client.getRescue(args.id);case 'join_rescue_network':{const r=await client.registerWorker(args.name);return {workerId:r.workerId,name:r.name,connected:true};}case 'list_rescue_jobs':return client.jobs();case 'claim_rescue':return client.claim(args.rescueId);case 'submit_rescue_patch':return client.submit(args.rescueId,args.code,{explanation:args.explanation});default:throw new Error('Unknown tool');}}
function reply(id,result,error){process.stdout.write(JSON.stringify(error?{jsonrpc:'2.0',id,error}:{jsonrpc:'2.0',id,result})+'\n');}
createInterface({input:process.stdin,crlfDelay:Infinity}).on('line',async line=>{let m;try{m=JSON.parse(line);}catch{reply(null,null,{code:-32700,message:'Invalid JSON'});return;}if(m.id===undefined)return;
 try{if(m.method==='initialize'){reply(m.id,{protocolVersion:['2024-11-05','2025-03-26','2025-06-18'].includes(m.params?.protocolVersion)?m.params.protocolVersion:'2024-11-05',capabilities:{tools:{listChanged:false}},serverInfo:{name:'mayday-agent-rescue',version:'1.0.0'},instructions:'When blocked on a JavaScript function, send_sos with real acceptance tests. Get the rescue and apply only a verified patch. To help other agents, join_rescue_network then list, claim and submit.'});}
 else if(m.method==='ping')reply(m.id,{});else if(m.method==='tools/list')reply(m.id,{tools});else if(m.method==='tools/call'){try{const result=await call(m.params.name,m.params.arguments??{});reply(m.id,{content:[{type:'text',text:JSON.stringify(result)}],isError:false});}catch(e){reply(m.id,{content:[{type:'text',text:e.message}],isError:true});}}else reply(m.id,null,{code:-32601,message:'Unknown method'});}catch(e){reply(m.id,null,{code:-32603,message:e.message});}});
